

def getTables(skima):
    query = []
    query.append("SELECT                 ")
    query.append("	OWNER                ")
    query.append("	,TABLE_NAME          ")
    query.append("	,COMMENTS            ")
    query.append("FROM all_tab_comments  ")
    query.append("WHERE 1=1              ")
    query.append(f"AND OWNER = '{skima}' ")
    query.append("AND TABLE_TYPE = 'TABLE'")

    return " ".join(query)

def getColunmsByTable(table,skima):
    query = []
    query.append(" SELECT                                                ")
    query.append("     A.TABLE_NAME,                                     ")
    query.append("     A.COLUMN_NAME,                                    ")
    query.append("     B.COMMENTS,                                       ")
    query.append("     A.DATA_TYPE,                                      ")
    query.append("     A.DATA_LENGTH,                                    ")
    query.append("     A.COLUMN_ID,                                      ")
    query.append("     A.NULLABLE,                                       ")
    query.append("     NVL(PK.CONSTRAINT_TYPE, ' ') AS IS_PRIMARY_KEY,   ")
    query.append("     NVL(FK.CONSTRAINT_TYPE, ' ') AS IS_FOREIGN_KEY    ")
    query.append(" FROM (                                                ")
    query.append("     SELECT                                            ")
    query.append("         TABLE_NAME,                                   ")
    query.append("         COLUMN_NAME,                                  ")
    query.append("         DATA_TYPE,                                    ")
    query.append("         DATA_LENGTH,                                  ")
    query.append("         COLUMN_ID,                                    ")
    query.append("         NULLABLE,                                     ")
    query.append("         DATA_DEFAULT                                  ")
    query.append("     FROM ALL_TAB_COLUMNS                              ")
    query.append(f"     WHERE OWNER = '{skima}'                          ")
    query.append("     ORDER BY TABLE_NAME, COLUMN_ID                    ")
    query.append(" ) A                                                   ")
    query.append(" LEFT JOIN (                                           ")
    query.append("     SELECT                                            ")
    query.append("         TABLE_NAME,                                   ")
    query.append("         COMMENTS,                                     ")
    query.append("         COLUMN_NAME                                   ")
    query.append("     FROM USER_COL_COMMENTS                            ")
    query.append(" ) B                                                   ")
    query.append(" ON A.TABLE_NAME = B.TABLE_NAME                        ")
    query.append(" AND A.COLUMN_NAME = B.COLUMN_NAME                     ")
    query.append(" LEFT JOIN (                                           ")
    query.append("     SELECT                                            ")
    query.append("         ACC.TABLE_NAME,                               ")
    query.append("         ACC.COLUMN_NAME,                              ")
    query.append("         AC.CONSTRAINT_TYPE                            ")
    query.append("     FROM ALL_CONS_COLUMNS ACC                         ")
    query.append("     JOIN ALL_CONSTRAINTS AC                           ")
    query.append("     ON ACC.CONSTRAINT_NAME = AC.CONSTRAINT_NAME       ")
    query.append("     AND ACC.OWNER = AC.OWNER                          ")
    query.append("     WHERE AC.CONSTRAINT_TYPE = 'P'                    ")
    query.append(f"     AND AC.OWNER = '{skima}'                         ")
    query.append(" ) PK                                                  ")
    query.append(" ON A.TABLE_NAME = PK.TABLE_NAME                       ")
    query.append(" AND A.COLUMN_NAME = PK.COLUMN_NAME                    ")
    query.append(" LEFT JOIN (                                           ")
    query.append("     SELECT                                            ")
    query.append("         ACC.TABLE_NAME,                               ")
    query.append("         ACC.COLUMN_NAME,                              ")
    query.append("         AC.CONSTRAINT_TYPE                            ")
    query.append("     FROM ALL_CONS_COLUMNS ACC                         ")
    query.append("     JOIN ALL_CONSTRAINTS AC                           ")
    query.append("     ON ACC.CONSTRAINT_NAME = AC.CONSTRAINT_NAME       ")
    query.append("     AND ACC.OWNER = AC.OWNER                          ")
    query.append("     WHERE AC.CONSTRAINT_TYPE = 'R'                    ")
    query.append(f"     AND AC.OWNER = '{skima}'                         ")
    query.append(" ) FK                                                  ")
    query.append(" ON A.TABLE_NAME = FK.TABLE_NAME                       ")
    query.append(" AND A.COLUMN_NAME = FK.COLUMN_NAME                    ")
    query.append(f" WHERE A.TABLE_NAME = '{table}'                      ")
    query.append(" ORDER BY A.TABLE_NAME, A.COLUMN_ID                    ")

    return " ".join(query)


def getTableIndexes(table,skima):
    query = []
    query.append("SELECT									 ")
    query.append("    idx.TABLE_NAME,                        ")
    query.append("    idx.INDEX_NAME,                        ")
    query.append("    idx.UNIQUENESS,                        ")
    query.append("    col.COLUMN_NAME,                       ")
    query.append("    col.DESCEND,                       ")
    query.append("    col.COLUMN_POSITION                    ")
    query.append("FROM                                       ")
    query.append("    all_indexes idx                        ")
    query.append("JOIN                                       ")
    query.append("    all_ind_columns col                    ")
    query.append("ON                                         ")
    query.append("    idx.index_name = col.index_name        ")
    query.append("    AND idx.owner = col.index_owner        ")
    query.append("WHERE                                      ")
    query.append(f"    idx.table_owner = '{skima}'           ")
    query.append(f"    AND idx.table_name = '{table}' ")
    query.append("ORDER BY                                   ")
    query.append("    idx.index_name,                        ")
    query.append("    col.column_position                    ")

    return " ".join(query)